---
services:
  python:
    container_name: python
    build:
      dockerfile: Dockerfile.python
    image: python
    restart: always
    ports:
      - 8050:8050
    volumes:
      - ./:/elt-practice-2024/
      - myapi_volume:/project_data/

volumes:
  myapi_volume:
