# Use the official Nginx image as the base
FROM nginx:alpine

# Remove the default Nginx HTML files
RUN rm -rf /usr/share/nginx/html/*

# Copy custom Nginx config
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 3000 to access the documentation
EXPOSE 3000

# Override the default Nginx config to use port 3000
CMD ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
