---
elt_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT') | as_number }}"
      dbname: "{{ env_var('DBT_POSTGRES_DB') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      pass: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      threads: "{{ env_var('DBT_POSTGRES_CONNECTION_LIMIT') | int }}"
