{% macro get_client_acme_membership_processed_columns() %}
        "member_id",
        "member_first_name",
        "member_middle_name",
        "member_last_name",
        "gender",
        {{ clean_date_of_birth("date_of_birth") }} AS "date_of_birth",
        "address",
        "city",
        {{ clean_invalid_values("state", ["'88'", "'ZZ'"]) }} AS "state",
        {{ clean_invalid_values("zip", ["'RTEFG'", "'123TY'"]) }} AS "zip",
        {{ clean_phone_number("phone_number") }} AS "phone_number",
        {{ clean_membership_end_date("membership_end_date", ["'2023-11-31'"]) }} AS "membership_end_date",
        "ethnicity",
        "client_name",
        "client_id",
        "internal_filename",
        "external_filename",
        "created_on",
        "modified_on"
{% endmacro %}