{% macro get_client_acme_membership_processed_columns() %}
    cast("member_id" as integer) as member_id,
    "client_id",
    cast({{ clean_invalid_values("membership_end_date", ["'2023-11-31'"]) }} as date) as "membership_end_date",
    "member_first_name",
    "member_middle_name",
    "member_last_name",
    "gender",
    {{ clean_date_of_birth("date_of_birth") }} as "date_of_birth",
    "address",
    "city",
    {{ clean_invalid_values("state", ["'88'", "'ZZ'"]) }} as "state",
    {{ clean_invalid_values("zip", ["'RTEFG'", "'123TY'"]) }} as "zip",
    {{ clean_phone_number("phone_number") }} as "phone_number",
    "ethnicity",
    "client_name",
    "internal_filename",
    "external_filename",
    "created_on",
    "modified_on"
{% endmacro %}
