---
name: Lint and Test through Docker
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - staging
      - 'release/**'
env:
  COMPOSE_PGADMIN_DEFAULT_EMAIL: ${{ secrets.COMPOSE_PGADMIN_DEFAULT_EMAIL }}
  COMPOSE_PGADMIN_DEFAULT_PASSWORD: ${{ secrets.COMPOSE_PGADMIN_DEFAULT_PASSWORD }}
  COMPOSE_POSTGRES_HOST: ${{ secrets.COMPOSE_POSTGRES_HOST }}
  COMPOSE_POSTGRES_PORT: ${{ secrets.COMPOSE_POSTGRES_PORT }}
  COMPOSE_POSTGRES_DB: ${{ secrets.COMPOSE_POSTGRES_DB }}
  COMPOSE_POSTGRES_SCHEMA: ${{ secrets.COMPOSE_POSTGRES_SCHEMA }}
  COMPOSE_POSTGRES_ADMIN_USER: ${{ secrets.COMPOSE_POSTGRES_ADMIN_USER }}
  COMPOSE_POSTGRES_ADMIN_PASSWORD: ${{ secrets.COMPOSE_POSTGRES_ADMIN_PASSWORD }}
  COMPOSE_POSTGRES_PYTHON_USER: ${{ secrets.COMPOSE_POSTGRES_PYTHON_USER }}
  COMPOSE_POSTGRES_PYTHON_PASSWORD: ${{ secrets.COMPOSE_POSTGRES_PYTHON_PASSWORD }}
  COMPOSE_POSTGRES_PYTHON_LIBPQ_CONNECTION_STRING: ${{ secrets.COMPOSE_POSTGRES_PYTHON_LIBPQ_CONNECTION_STRING }}
  COMPOSE_POSTGRES_PYTHON_CONNECTION_LIMIT: ${{ secrets.COMPOSE_POSTGRES_PYTHON_CONNECTION_LIMIT }}
  COMPOSE_DBT_POSTGRES_USER: ${{ secrets.COMPOSE_DBT_POSTGRES_USER }}
  COMPOSE_DBT_POSTGRES_PASSWORD: ${{ secrets.COMPOSE_DBT_POSTGRES_PASSWORD }}
  COMPOSE_DBT_POSTGRES_SCHEMA: ${{ secrets.COMPOSE_DBT_POSTGRES_SCHEMA }}
  COMPOSE_DBT_POSTGRES_CONNECTION_LIMIT: ${{ secrets.COMPOSE_DBT_POSTGRES_CONNECTION_LIMIT }}
  COMPOSE_DBT_POSTGRES_READ_ROLE: ${{ secrets.COMPOSE_DBT_POSTGRES_READ_ROLE }}
  COMPOSE_DBT_POSTGRES_WRITE_ROLE: ${{ secrets.COMPOSE_DBT_POSTGRES_WRITE_ROLE }}
  COMPOSE_DBT_PROFILES_DIR: ${{ secrets.COMPOSE_DBT_PROFILES_DIR }}
  COMPOSE_DBT_PROJECT_DIR: ${{ secrets.COMPOSE_DBT_PROJECT_DIR }}

jobs:
  lint_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo and set environment variables
        uses: actions/checkout@v4
      - name: Spin up docker containers
        run: docker compose up --detach --build --force-recreate --remove-orphans postgres pgadmin python nginx
      - name: Wait a few seconds to allow services to be functional
        run: sleep 6s
      - name: Run linters
        run: |
          docker exec python hadolint \
            Dockerfile.python \
            Dockerfile.postgres \
            Dockerfile.pgadmin
          docker exec python yamllint \
            compose.yml \
            .github/workflows/lint_and_test.yaml \
            .hadolint.yaml \
            .pre-commit-config.yaml
          docker exec python flake8 src/
          docker exec python vulture src/
          docker exec python black src/ --check
          docker exec python mypy src/elt_practice_2024/
          docker exec python sqlfluff lint src/elt_dbt/
          docker compose run --rm dbt deps
          docker compose run --rm dbt parse
      - name: Run python tests
        run: docker exec python pytest .
      - name: Spin down docker services
        run: docker compose down
